### PR TITLE
Apply CMS patches to version 2.3.1.1.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@civanch @dr15jones This is the patch I obtained comparing 2.2.0.4 and the CMS branch, ported over the 2.3.1.1 version. There was no conflict. Can you please confirm that it looks reasonable?

**Comment by Dr15Jones** [comment]
I guess it is fine. Wish I remembered why we did some of those changes.

**Comment by civanch** [comment]
It is OK to me.

**Comment by davidlange6** [comment]
me too… anyone can tell from when we started these patches?
[I understand the unused variables one that maybe we should feed back - but otherwise we un-inlined some trivial functions]

**Comment by ghost** [comment]
Tested compilation locally. Will now merge.

**Comment by civanch** [comment]
@davidlange6, there were some fixes already applied in past (mainly for random generators), so our 2.2.0.4 was patched.

**Comment by davidlange6** [comment]
yes, but do we know _why_ we needed the fixes (e.g., any historical memory)? its not good to have patches that apparently no one less needs unless its for a good reason..

**Pull request merged**
